#!/usr/bin/env python3
"""Prints test/p256_ecdh_vectors.h: P-256 key pairs, shared secrets and the
points a key exchange must refuse.

Every point here comes from Python's own arbitrary-precision arithmetic over
the affine curve equation, not from the C under test, so the vectors are an
independent answer rather than a recording of what p256_ecdh.c does. The
scalar multiply below is double-and-add over affine coordinates with an
inversion per step: the slowest way to write it, and the one that shares no
formula with the projective complete addition the C file runs.

The curve constants p256_ecdh.c carries are repeated here and checked: b and
the generator satisfy the curve equation, n*G is the point at infinity, and
(n-1)*G is -G. A typo in either place fails those checks.

Usage: python3 test/gen_p256_ecdh_vectors.py > test/p256_ecdh_vectors.h
"""

import random

P = 2**256 - 2**224 + 2**192 + 2**96 - 1
B = 0x5AC635D8AA3A93E7B3EBBD55769886BC651D06B0CC53B0F63BCE3C3E27D2604B
N = 0xFFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551
GX = 0x6B17D1F2E12C4247F8BCE6E563A440F277037D812DEB33A0F4A13945D898C296
GY = 0x4FE342E2FE1A7F9B8EE7EB4A7C0F9E162BCE33576B315ECECBB6406837BF51F5
G = (GX, GY)


def on_curve(point):
    x, y = point
    return (y * y - x * x * x + 3 * x - B) % P == 0


def add(point_a, point_b):
    """The affine group law. None is the point at infinity."""
    if point_a is None:
        return point_b
    if point_b is None:
        return point_a
    x1, y1 = point_a
    x2, y2 = point_b
    if x1 == x2 and (y1 + y2) % P == 0:
        return None
    if point_a == point_b:
        lam = (3 * x1 * x1 - 3) * pow(2 * y1, -1, P) % P
    else:
        lam = (y2 - y1) * pow(x2 - x1, -1, P) % P
    x3 = (lam * lam - x1 - x2) % P
    return (x3, (lam * (x1 - x3) - y1) % P)


def mul(k, point):
    acc = None
    addend = point
    while k:
        if k & 1:
            acc = add(acc, addend)
        addend = add(addend, addend)
        k >>= 1
    return acc


def check_constants():
    assert on_curve(G), "the generator does not satisfy y^2 = x^3 - 3x + b"
    assert mul(N, G) is None, "n*G is not the point at infinity"
    assert mul(N - 1, G) == (GX, (-GY) % P), "(n-1)*G is not -G"


def smallest_x():
    """The smallest x with a point on the curve. Its encoding plus p still
    fits in 32 bytes, which is what makes the range-check case below."""
    x = 0
    while True:
        rhs = (x * x * x - 3 * x + B) % P
        y = pow(rhs, (P + 1) // 4, P)  # p = 3 mod 4, so this is the root
        if y * y % P == rhs:
            return (x, y)
        x += 1


def hex32(value):
    return value.to_bytes(32, "big")


def point_bytes(point):
    return b"\x04" + hex32(point[0]) + hex32(point[1])


def c_bytes(data, indent):
    rows = [", ".join("0x%02x" % b for b in data[i:i + 13]) for i in range(0, len(data), 13)]
    pad = " " * (indent + 1)
    return "{" + (",\n" + pad).join(rows) + "}"


def scalar_const(name, value):
    return f"static const uint8_t {name}[32] = " + "{\n    " + c_bytes(hex32(value), 3)[1:] + ";"


def keygen_case(comment, scalar):
    pub = mul(scalar, G)
    assert on_curve(pub)
    return (f"    // {comment}\n"
            "    {" + c_bytes(hex32(scalar), 5) + ",\n"
            "     " + c_bytes(point_bytes(pub), 5) + "},")


def shared_case(comment, priv, peer):
    product = mul(priv, peer)
    assert on_curve(peer) and on_curve(product)
    return (f"    // {comment}\n"
            "    {" + c_bytes(hex32(priv), 5) + ",\n"
            "     " + c_bytes(point_bytes(peer), 5) + ",\n"
            "     " + c_bytes(hex32(product[0]), 5) + "},")


def bad_point_case(comment, encoding):
    assert len(encoding) == 65
    return (f"    // {comment}\n"
            "    {" + c_bytes(encoding, 5) + "},")


def main():
    check_constants()
    random.seed(20260919)  # fixed, so a rerun over an unchanged tree reproduces the header
    small = smallest_x()
    peers = [mul(random.randrange(1, N), G) for _ in range(3)]

    out = [
        "// Generated by test/gen_p256_ecdh_vectors.py — do not edit by hand.",
        "// P-256 key pairs, shared secrets and refused points, all computed",
        "// with Python's affine arithmetic rather than with the C under test.",
        "// The script is also the formatter: the off marker keeps",
        "// regeneration byte-identical under any clang-format version, or none.",
        "#ifndef CH_P256_ECDH_VECTORS_H",
        "#define CH_P256_ECDH_VECTORS_H",
        "",
        "#include <stdint.h>",
        "",
        "// clang-format off",
        "",
        "typedef struct {",
        "    uint8_t scalar[32];",
        "    uint8_t pub[65];",
        "} p256_ecdh_keygen_case;",
        "",
        "static const p256_ecdh_keygen_case P256_ECDH_KEYGEN[] = {",
        keygen_case("the smallest scalar", 1),
        keygen_case("2, the first doubling", 2),
        keygen_case("the largest scalar, n-1", N - 1),
        keygen_case("a scalar with the top bit set", N - 2),
        keygen_case("a scalar whose leading 16 bytes are zero", 0x2A3F),
    ]
    for i in range(3):
        out.append(keygen_case(f"a random scalar ({i + 1} of 3)", random.randrange(1, N)))
    out += [
        "};",
        "",
        "typedef struct {",
        "    uint8_t priv[32];",
        "    uint8_t peer[65];",
        "    uint8_t shared[32];",
        "} p256_ecdh_shared_case;",
        "",
        "static const p256_ecdh_shared_case P256_ECDH_SHARED[] = {",
        shared_case("the generator as the peer point", 0x2A3F, G),
        shared_case("the smallest x on the curve as the peer point", N - 1, small),
    ]
    for i, peer in enumerate(peers):
        out.append(shared_case(f"a random pair ({i + 1} of 3)", random.randrange(1, N), peer))
    out += [
        "};",
        "",
        "// Points p256_ecdh_point_valid must refuse. Each comment names which",
        "// check refuses it.",
        "typedef struct {",
        "    uint8_t point[65];",
        "} p256_ecdh_bad_point;",
        "",
        "static const p256_ecdh_bad_point P256_ECDH_BAD_POINT[] = {",
        bad_point_case("the leading byte is 2, a compressed encoding",
                       b"\x02" + point_bytes(peers[0])[1:]),
        bad_point_case("the leading byte is 0, the point at infinity",
                       b"\x00" + point_bytes(peers[0])[1:]),
        bad_point_case("x is at or above p: x = p, the first value that is not an element",
                       b"\x04" + hex32(P) + hex32(peers[0][1])),
        bad_point_case("y is at or above p: y = p",
                       b"\x04" + hex32(peers[0][0]) + hex32(P)),
        bad_point_case("x is at or above p: x + p for a point that is on the curve",
                       b"\x04" + hex32(small[0] + P) + hex32(small[1])),
        bad_point_case("off the curve: y is one greater than a root",
                       b"\x04" + hex32(peers[0][0]) + hex32((peers[0][1] + 1) % P)),
        bad_point_case("off the curve: (0, 0)", b"\x04" + hex32(0) + hex32(0)),
        "};",
        "",
        "// The scalar boundary: the last value in range and the first out of it.",
        scalar_const("P256_ECDH_SCALAR_LAST", N - 1),
        scalar_const("P256_ECDH_SCALAR_FIRST_BAD", N),
        # N is refused twice over: the range check rejects it, and N*G is
        # the point at infinity, which the affine mask rejects on its own.
        # N+1 separates them. It is out of range, and (N+1)*G is G, a
        # finite point, so only the range check can refuse it.
        scalar_const("P256_ECDH_SCALAR_ABOVE_ORDER", N + 1),
        scalar_const("P256_ECDH_SCALAR_ZERO", 0),
        scalar_const("P256_ECDH_SCALAR_ONE", 1),
        "",
        "// clang-format on",
        "",
        "#endif",
    ]
    print("\n".join(out))


if __name__ == "__main__":
    main()
