#!/usr/bin/env python3
# Generates test/mlkem_vectors.h: ML-KEM-768 known-answer vectors.
#
# Two provenances, both checked into the header so the test binary needs
# no network and no ML-KEM implementation of its own:
#
#  1. Seed KATs (keygen + encaps + decaps round trip). Derived from
#     kyber-py, a FIPS 203 implementation, under deterministic seeds
#     d/z/m = SHAKE256(tag || counter). kyber-py's decaps was checked
#     byte-for-byte against the authoritative C2SP/CCTV vectors below,
#     so its keygen/encaps output is trustworthy for these seeds.
#
#  2. C2SP/CCTV authoritative decaps vectors (CC0), derived from the
#     pq-crystals reference. `decaps` is the top-level ML-KEM.Decaps
#     vector; `strcmp` is CCTV's vector that fails if ML-KEM.Decaps
#     compares with strcmp instead of a constant-time equality — it
#     exercises the implicit-reject path with an embedded zero byte.
#     https://c2sp.org/CCTV/ML-KEM
#
# Refresh: `python3 test/gen_mlkem_vectors.py` (needs `pip install
# kyber-py`). The CCTV literals are embedded below; update them from
# the CCTV repo if the upstream vectors change.
import hashlib

# C2SP/CCTV ML-KEM-768 authoritative decaps vectors (dk, c, K), hex.
CCTV = {
    "decaps": None,  # filled from intermediate/ML-KEM-768.txt
    "strcmp": None,  # filled from strcmp/ML-KEM-768.txt
}


def load_cctv():
    """The two CCTV decaps vectors, embedded as hex triples."""
    import json
    import os
    here = os.path.dirname(os.path.abspath(__file__))
    src = os.path.join(here, "mlkem_cctv.json")
    with open(src) as f:
        d = json.load(f)
    return d["decaps"], d["strcmp"]


def kdf(tag, n):
    return hashlib.shake_256(tag + n.to_bytes(2, "big")).digest(32)


def carr(name, b):
    items = [f"0x{x:02x}" for x in b]
    lines = [", ".join(items[i : i + 12]) for i in range(0, len(items), 12)]
    return f"static const uint8_t {name}[] = {{\n    " + ",\n    ".join(lines) + "};\n"


def main():
    from kyber_py.ml_kem import ML_KEM_768 as M

    decaps, strcmp = load_cctv()
    out = [
        "// Generated by test/gen_mlkem_vectors.py. Do not edit by hand.",
        "// ML-KEM-768 known-answer vectors, full bytes for exact comparison.",
        "// Seed KATs from kyber-py; decaps/strcmp from C2SP/CCTV (CC0).",
        "#ifndef CH_MLKEM_VECTORS_H",
        "#define CH_MLKEM_VECTORS_H",
        "",
        "#include <stdint.h>",
        "",
    ]
    n_kat = 4
    out.append(f"#define MLKEM_KAT_COUNT {n_kat}\n")
    for i in range(n_kat):
        d, z, m = kdf(b"d", i), kdf(b"z", i), kdf(b"m", i)
        ek, dk = M._keygen_internal(d, z)
        K, ct = M._encaps_internal(ek, m)
        assert M._decaps_internal(dk, ct) == K
        for nm, val in [("d", d), ("z", z), ("m", m), ("ek", ek), ("dk", dk), ("ct", ct), ("K", K)]:
            out.append(carr(f"mlk_kat{i}_{nm}", val))
    for nm in ["d", "z", "m", "ek", "dk", "ct", "K"]:
        out.append(
            f"static const uint8_t *const mlk_kat_{nm}[MLKEM_KAT_COUNT] = {{"
            + ", ".join(f"mlk_kat{i}_{nm}" for i in range(n_kat))
            + "};"
        )
    out.append("")
    for tag, tri in [("decaps", decaps), ("strcmp", strcmp)]:
        dk = bytes.fromhex(tri[0])
        c = bytes.fromhex(tri[1])
        k = bytes.fromhex(tri[2])
        out.append(carr(f"mlk_{tag}_dk", dk))
        out.append(carr(f"mlk_{tag}_ct", c))
        out.append(carr(f"mlk_{tag}_ss", k))
    out.append("")
    out.append("#endif")
    import os

    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, "mlkem_vectors.h"), "w") as f:
        f.write("\n".join(out))
    print(f"wrote mlkem_vectors.h: {n_kat} seed KATs + CCTV decaps + strcmp")


if __name__ == "__main__":
    main()
