#!/usr/bin/env python3
"""Regenerates test/rsa_pkcs1_vectors.h.

Usage: python3 test/gen_rsa_pkcs1_vectors.py

The script mints two fresh RSA keys with OpenSSL 3 and signs four fixed
messages with RSASSA-PKCS1-v1_5, the signature scheme a public CA
writes on a certificate (sha256WithRSAEncryption and
sha384WithRSAEncryption, RFC 8017 section 8.2). The keys are fresh on
every run, so the committed header changes when it is regenerated;
vectors are regenerate-never-edit snapshots.

The exact commands, per key size in {2048, 3072}:

  openssl genrsa -out key.pem <bits>
  openssl rsa -in key.pem -noout -modulus
  openssl dgst -sha256 -binary msg                      (the digest)
  openssl dgst -sha256 -sign key.pem -out sig msg       (PKCS#1 v1.5)
  openssl dgst -sha384 -binary msg
  openssl dgst -sha384 -sign key.pem -out sig msg

and one RSA-PSS signature under the 2048-bit key, which the test
requires the PKCS#1 v1.5 verifier to refuse:

  openssl dgst -sha256 -sign key.pem -sigopt rsa_padding_mode:pss
    -sigopt rsa_pss_saltlen:32 -out sig msg

Every signature is checked with `openssl dgst -verify` before it is
emitted, so a wrong invocation fails here instead of shipping a
misleading vector.
"""

import os
import pathlib
import shutil
import subprocess
import sys
import tempfile

OUT = pathlib.Path(__file__).with_name("rsa_pkcs1_vectors.h")

# (name, bits, hash, message). One message per key size and hash so a
# vector that fails names its own case.
CASES = [
    ("rsa2048_sha256", 2048, "sha256", b"chapulin pkcs1 vector one"),
    ("rsa2048_sha384", 2048, "sha384", b"chapulin pkcs1 vector two"),
    ("rsa3072_sha256", 3072, "sha256", b"chapulin pkcs1 vector three"),
    ("rsa3072_sha384", 3072, "sha384", b"chapulin pkcs1 vector four"),
]
PSS_MESSAGE = b"chapulin pkcs1 vector one"

# The DigestInfo prefixes rsa_pkcs1.c carries (RFC 8017 section 9.2 note 1).
# Each signature's encoded message is recovered with
#   openssl pkeyutl -verifyrecover -pubin -inkey pub.pem -in sig
#     -pkeyopt rsa_padding_mode:none
# and checked to be 0x00 0x01, 0xff bytes, 0x00, the prefix and the digest,
# so the constants are measured against openssl, never copied on trust.
DIGEST_INFO = {
    "sha256": bytes.fromhex("3031300d060960864801650304020105000420"),
    "sha384": bytes.fromhex("3041300d060960864801650304020205000430"),
}


def sh(*cmd, stdin=None):
    r = subprocess.run(cmd, input=stdin, capture_output=True)
    if r.returncode != 0:
        sys.exit(f"{cmd[0]} failed: {r.stderr.decode()[:400]}")
    return r.stdout


def c_array(name, data, comment):
    lines = [f"// {line}" for line in comment.splitlines()]
    lines.append(f"static const uint8_t {name}[] = {{")
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i : i + 16])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    ossl = shutil.which("openssl", path="/opt/homebrew/bin:/usr/bin:" + (os.environ.get("PATH") or ""))
    if ossl is None:
        sys.exit("openssl not found")
    version = sh(ossl, "version").decode().strip().split(" (")[0]

    with tempfile.TemporaryDirectory() as tmp:
        t = pathlib.Path(tmp)
        keys = {}
        moduli = {}
        for bits in (2048, 3072):
            key = t / f"key{bits}.pem"
            sh(ossl, "genrsa", "-out", str(key), str(bits))
            pub = t / f"pub{bits}.pem"
            sh(ossl, "rsa", "-in", str(key), "-pubout", "-out", str(pub))
            modulus = sh(ossl, "rsa", "-in", str(key), "-noout", "-modulus")
            n = bytes.fromhex(modulus.decode().split("=")[1].strip())
            if len(n) != bits // 8 or n[0] & 0x80 == 0 or n[-1] & 1 == 0:
                sys.exit(f"modulus shape wrong at {bits}")
            keys[bits] = (key, pub)
            moduli[bits] = n

        out = [
            "// RSASSA-PKCS1-v1_5 vectors for test/rsa_pkcs1_test.c. Generated by",
            "// test/gen_rsa_pkcs1_vectors.py, which quotes the openssl commands;",
            f"// regenerate, never edit. Produced with {version}.",
            "#ifndef CH_TEST_RSA_PKCS1_VECTORS_H",
            "#define CH_TEST_RSA_PKCS1_VECTORS_H",
            "",
            "#include <stdint.h>",
            "",
        ]
        for bits in (2048, 3072):
            out.append(
                c_array(
                    f"n{bits}",
                    moduli[bits],
                    f"RSA-{bits} modulus, big-endian. Source: openssl rsa -noout -modulus.",
                )
            )
        for name, bits, digest_name, message in CASES:
            key, pub = keys[bits]
            msg = t / f"{name}.msg"
            msg.write_bytes(message)
            sig = t / f"{name}.sig"
            digest = sh(ossl, "dgst", f"-{digest_name}", "-binary", str(msg))
            sh(ossl, "dgst", f"-{digest_name}", "-sign", str(key), "-out", str(sig), str(msg))
            sh(ossl, "dgst", f"-{digest_name}", "-verify", str(pub), "-signature", str(sig), str(msg))
            sig_bytes = sig.read_bytes()
            if len(sig_bytes) != bits // 8:
                sys.exit(f"signature length wrong at {name}")
            em = sh(ossl, "pkeyutl", "-verifyrecover", "-pubin", "-inkey", str(pub), "-in", str(sig),
                    "-pkeyopt", "rsa_padding_mode:none")
            tail = DIGEST_INFO[digest_name] + digest
            ps_len = len(em) - 3 - len(tail)
            if em != b"\x00\x01" + b"\xff" * ps_len + b"\x00" + tail:
                sys.exit(f"encoded message shape wrong at {name}")
            out.append(f'static const char {name}_message[] = "{message.decode()}";')
            out.append(
                c_array(
                    f"{name}_digest",
                    digest,
                    f"openssl dgst -{digest_name} -binary over {name}_message.",
                )
            )
            out.append(
                c_array(
                    f"{name}_sig",
                    sig_bytes,
                    f"openssl dgst -{digest_name} -sign key{bits}.pem over {name}_message:\n"
                    f"RSASSA-PKCS1-v1_5 under n{bits}.",
                )
            )

        key, pub = keys[2048]
        msg = t / "pss.msg"
        msg.write_bytes(PSS_MESSAGE)
        sig = t / "pss.sig"
        pss = ["-sigopt", "rsa_padding_mode:pss", "-sigopt", "rsa_pss_saltlen:32"]
        sh(ossl, "dgst", "-sha256", "-sign", str(key), *pss, "-out", str(sig), str(msg))
        sh(ossl, "dgst", "-sha256", "-verify", str(pub), *pss, "-signature", str(sig), str(msg))
        out.append(
            c_array(
                "rsa2048_sha256_pss_sig",
                sig.read_bytes(),
                "openssl dgst -sha256 -sign key2048.pem -sigopt rsa_padding_mode:pss\n"
                "  -sigopt rsa_pss_saltlen:32 over rsa2048_sha256_message: an RSA-PSS\n"
                "signature under n2048 over the same digest as rsa2048_sha256_sig.\n"
                "The PKCS#1 v1.5 verifier must refuse it.",
            )
        )
        out.append("#endif")
        OUT.write_text("\n".join(out) + "\n")
        print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
