#!/usr/bin/env python3
"""Prints test/p256_field_vectors.h: arithmetic mod the P-256 prime.

Every number here comes from Python's arbitrary-precision integers, not from
the C under test, so the vectors are an independent answer rather than a
recording of what p256_field.c does. The prime, the two Montgomery constants
and the Fermat exponent are recomputed from p's definition and compared with
the limbs p256_field.c carries, so a typo in either place fails here.

Usage: python3 test/gen_p256_field_vectors.py > test/p256_field_vectors.h
"""

import random

P = 2**256 - 2**224 + 2**192 + 2**96 - 1
R = 2**256
R_INV = pow(R, -1, P)

# The limbs p256_field.c carries, repeated here so this script checks them.
C_P = [0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF, 0x00000000,
       0x00000000, 0x00000000, 0x00000001, 0xFFFFFFFF]
C_RR = [0x00000003, 0x00000000, 0xFFFFFFFF, 0xFFFFFFFB,
        0xFFFFFFFE, 0xFFFFFFFF, 0xFFFFFFFD, 0x00000004]
C_ONE_MONT = [0x00000001, 0x00000000, 0x00000000, 0xFFFFFFFF,
              0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFE, 0x00000000]
C_P_MINUS_2 = [0xFFFFFFFD, 0xFFFFFFFF, 0xFFFFFFFF, 0x00000000,
               0x00000000, 0x00000000, 0x00000001, 0xFFFFFFFF]


def limbs(x):
    return [(x >> (32 * i)) & 0xFFFFFFFF for i in range(8)]


def check_constants():
    assert limbs(P) == C_P, "p256_field.c's P is not the P-256 prime"
    assert limbs(R * R % P) == C_RR, "p256_field.c's RR is not 2^512 mod p"
    assert limbs(R % P) == C_ONE_MONT, "p256_field.c's one_mont is not R mod p"
    assert limbs(P - 2) == C_P_MINUS_2, "p256_field.c's exponent is not p-2"


def be(x, indent):
    """One 32-byte big-endian value, sixteen bytes to a line."""
    data = x.to_bytes(32, "big")
    rows = [", ".join("0x%02x" % b for b in data[i:i + 16]) for i in (0, 16)]
    pad = " " * (indent + 1)
    return "{" + rows[0] + ",\n" + pad + rows[1] + "}"


def case(name, a, b):
    assert 0 <= a < P and 0 <= b < P
    out = [f'    {{"{name}",\n']
    for value in (a, b, (a + b) % P, (a - b) % P, a * b % P, a * b * R_INV % P):
        out.append("     " + be(value, 5) + ",\n")
    return "".join(out)[:-2] + "},\n"


def inv_case(name, a):
    inv = pow(a, P - 2, P)
    if a % P:
        assert a * inv % P == 1
    return (f'    {{"{name}",\n'
            f"     {be(a, 5)},\n"
            f"     {be(inv, 5)}}},\n")


def main():
    check_constants()
    gx = 0x6B17D1F2E12C4247F8BCE6E563A440F277037D812DEB33A0F4A13945D898C296
    gy = 0x4FE342E2FE1A7F9B8EE7EB4A7C0F9E162BCE33576B315ECECBB6406837BF51F5
    curve_b = 0x5AC635D8AA3A93E7B3EBBD55769886BC651D06B0CC53B0F63BCE3C3E27D2604B

    cases = [
        ("zero and zero", 0, 0),
        ("zero and one", 0, 1),
        ("one and zero", 1, 0),
        # The exact boundary: the last element and the first value past it.
        ("last element plus one", P - 1, 1),
        ("last element twice", P - 1, P - 1),
        ("zero minus one", 0, 1),
        ("one minus last element", 1, P - 1),
        ("R minus one, the reduction step's other side", R % P, 1),
        ("generator coordinates", gx, gy),
        ("curve b and the generator's x", curve_b, gx),
    ]
    rng = random.Random(20260918)
    for i in range(12):
        cases.append((f"random {i}", rng.randrange(P), rng.randrange(P)))

    invs = [
        ("zero has no inverse and gives zero", 0),
        ("one", 1),
        ("two", 2),
        ("last element", P - 1),
        ("generator x", gx),
    ]
    rng = random.Random(9846)
    for i in range(5):
        invs.append((f"random {i}", rng.randrange(1, P)))

    out = []
    out.append("// Generated by test/gen_p256_field_vectors.py; regenerate, never edit.\n")
    out.append("// Arithmetic modulo the P-256 prime, computed in Python.\n")
    out.append("// Each case holds a, b, (a+b) mod p, (a-b) mod p, (a*b) mod p and\n")
    out.append("// (a*b/R) mod p, every number 32 big-endian bytes. The script is also\n")
    out.append("// the formatter: the off marker below keeps regeneration byte-identical\n")
    out.append("// under any clang-format version, or none.\n")
    out.append("#ifndef CH_TEST_P256_FIELD_VECTORS_H\n")
    out.append("#define CH_TEST_P256_FIELD_VECTORS_H\n\n")
    out.append("#include <stdint.h>\n\n")
    out.append("typedef struct {\n    const char *name;\n")
    for field in ("a", "b", "sum", "diff", "product", "mont_product"):
        out.append(f"    uint8_t {field}[32];\n")
    out.append("} p256_field_case;\n\n")
    out.append("typedef struct {\n    const char *name;\n    uint8_t a[32];\n"
               "    uint8_t inverse[32];\n} p256_field_inv_case;\n\n")
    out.append("// clang-format off\n")
    out.append("static const p256_field_case P256_FIELD_CASES[] = {\n")
    for name, a, b in cases:
        out.append(case(name, a, b))
    out.append("};\n\n")
    out.append("static const p256_field_inv_case P256_FIELD_INV_CASES[] = {\n")
    for name, a in invs:
        out.append(inv_case(name, a))
    out.append("};\n")
    out.append("// clang-format on\n\n#endif\n")
    print("".join(out), end="")


if __name__ == "__main__":
    main()
