#!/usr/bin/env python3
"""Regenerates test/rsa_wide_vectors.h and test/rsa_pkcs1_wide_vectors.h.

Usage: python3 test/gen_rsa_wide_vectors.py

The script mints two fresh RSA keys with OpenSSL 3 at the top of the
TRUST=webpki modulus range and one step below it: RSA-4096, whose modulus
is the 512 bytes CH_RSA_MODULUS_MAX names under CH_TRUST_WEBPKI (rsa.h),
and RSA-4032, 504 bytes, one 8-byte step down. It signs one message per
key three ways: RSASSA-PSS over SHA-256, the CertificateVerify scheme
rsa_pss_verify checks, and RSASSA-PKCS1-v1_5 over SHA-256 and over
SHA-384, the certificate signatures rsa_pkcs1_verify checks (RFC 8017
sections 8.1 and 8.2).

Two headers, split by who reads them. test/rsa_wide_vectors.h carries
the moduli, the messages, their SHA-256 digests and the PSS signatures:
test/rsa_test.c verifies them where the build admits a 512-byte modulus,
test/unit_test.c checks that the device build refuses them, and
test/rsa_pkcs1_test.c uses the PSS signature as the algorithm-confusion
case. test/rsa_pkcs1_wide_vectors.h carries the SHA-384 digests and the
PKCS#1 v1.5 signatures, which only test/rsa_pkcs1_test.c reads; every
binary that includes a header uses every array in it, so no build warns
about an unused vector. The keys are fresh on every run, so the
committed headers change when they are regenerated; vectors are
regenerate-never-edit snapshots.

The exact commands, per key size in {4096, 4032}:

  openssl genrsa -out key.pem <bits>
  openssl rsa -in key.pem -noout -modulus
  openssl dgst -sha256 -binary msg                      (the digest)
  openssl dgst -sha256 -sign key.pem -sigopt rsa_padding_mode:pss
    -sigopt rsa_pss_saltlen:32 -sigopt rsa_mgf1_md:sha256 -out sig msg
  openssl dgst -sha256 -sign key.pem -out sig msg       (PKCS#1 v1.5)
  openssl dgst -sha384 -binary msg
  openssl dgst -sha384 -sign key.pem -out sig msg

Every signature is checked with `openssl dgst -verify` before it is
emitted, and each PKCS#1 v1.5 encoded message is recovered with
`openssl pkeyutl -verifyrecover` and checked against the DigestInfo
prefix rsa_pkcs1.c carries, as test/gen_rsa_pkcs1_vectors.py does, so a
wrong invocation fails here instead of shipping a misleading vector.
"""

import os
import pathlib
import shutil
import subprocess
import sys
import tempfile

HERE = pathlib.Path(__file__).parent
OUT_PSS = HERE / "rsa_wide_vectors.h"
OUT_PKCS1 = HERE / "rsa_pkcs1_wide_vectors.h"

# (bits, message). One message per key; the three signatures over it
# share the digest, which is what makes the PSS one an
# algorithm-confusion case for the v1.5 verifier.
KEYS = [
    (4096, b"chapulin rsa-4096 vector"),
    (4032, b"chapulin rsa-4032 vector"),
]

# The DigestInfo prefixes rsa_pkcs1.c carries (RFC 8017 section 9.2 note 1).
DIGEST_INFO = {
    "sha256": bytes.fromhex("3031300d060960864801650304020105000420"),
    "sha384": bytes.fromhex("3041300d060960864801650304020205000430"),
}


def sh(*cmd, stdin=None):
    r = subprocess.run(cmd, input=stdin, capture_output=True)
    if r.returncode != 0:
        sys.exit(f"{cmd[0]} failed: {r.stderr.decode()[:400]}")
    return r.stdout


def c_array(name, data, comment):
    lines = [f"// {line}" for line in comment.splitlines()]
    lines.append(f"static const uint8_t {name}[] = {{")
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i : i + 16])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def header(guard, purpose, version):
    return [
        f"// {purpose} Generated by",
        "// test/gen_rsa_wide_vectors.py, which quotes the openssl commands;",
        f"// regenerate, never edit. Produced with {version}.",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <stdint.h>",
        "",
    ]


def pkcs1_sign(ossl, key, pub, digest_name, msg, sig, digest):
    """Signs msg with PKCS#1 v1.5 over digest_name, verifies the signature
    with openssl, and checks the recovered encoded message byte for byte."""
    sh(ossl, "dgst", f"-{digest_name}", "-sign", str(key), "-out", str(sig), str(msg))
    sh(ossl, "dgst", f"-{digest_name}", "-verify", str(pub), "-signature", str(sig), str(msg))
    em = sh(ossl, "pkeyutl", "-verifyrecover", "-pubin", "-inkey", str(pub), "-in", str(sig),
            "-pkeyopt", "rsa_padding_mode:none")
    tail = DIGEST_INFO[digest_name] + digest
    ps_len = len(em) - 3 - len(tail)
    if em != b"\x00\x01" + b"\xff" * ps_len + b"\x00" + tail:
        sys.exit(f"encoded message shape wrong at {sig.name}")
    return sig.read_bytes()


def main():
    ossl = shutil.which("openssl", path="/opt/homebrew/bin:/usr/bin:" + (os.environ.get("PATH") or ""))
    if ossl is None:
        sys.exit("openssl not found")
    version = sh(ossl, "version").decode().strip().split(" (")[0]

    pss_out = header("CH_TEST_RSA_WIDE_VECTORS_H",
                     "RSA-4096 and RSA-4032 moduli, digests and RSA-PSS signatures.", version)
    pkcs1_out = header("CH_TEST_RSA_PKCS1_WIDE_VECTORS_H",
                       "RSA-4096 and RSA-4032 RSASSA-PKCS1-v1_5 signatures.", version)
    # The v1.5 header reads the moduli and digests from the PSS one; its
    # own include block, as clang-format keeps blocks apart.
    pkcs1_out[7:7] = ["", '#include "rsa_wide_vectors.h"']
    with tempfile.TemporaryDirectory() as tmp:
        t = pathlib.Path(tmp)
        for bits, message in KEYS:
            name = f"rsa{bits}"
            key = t / f"key{bits}.pem"
            sh(ossl, "genrsa", "-out", str(key), str(bits))
            pub = t / f"pub{bits}.pem"
            sh(ossl, "rsa", "-in", str(key), "-pubout", "-out", str(pub))
            modulus = sh(ossl, "rsa", "-in", str(key), "-noout", "-modulus")
            n = bytes.fromhex(modulus.decode().split("=")[1].strip())
            if len(n) != bits // 8 or n[0] & 0x80 == 0 or n[-1] & 1 == 0:
                sys.exit(f"modulus shape wrong at {bits}")
            pss_out.append(c_array(
                f"n{bits}", n,
                f"RSA-{bits} modulus, {len(n)} bytes big-endian. Source: openssl rsa -noout -modulus."))

            msg = t / f"{name}.msg"
            msg.write_bytes(message)
            pss_out.append(f'static const char {name}_message[] = "{message.decode()}";')
            digest256 = sh(ossl, "dgst", "-sha256", "-binary", str(msg))
            pss_out.append(c_array(f"{name}_sha256_digest", digest256,
                                   f"openssl dgst -sha256 -binary over {name}_message."))

            sig = t / f"{name}.pss.sig"
            pss = ["-sigopt", "rsa_padding_mode:pss", "-sigopt", "rsa_pss_saltlen:32",
                   "-sigopt", "rsa_mgf1_md:sha256"]
            sh(ossl, "dgst", "-sha256", "-sign", str(key), *pss, "-out", str(sig), str(msg))
            sh(ossl, "dgst", "-sha256", "-verify", str(pub), *pss, "-signature", str(sig), str(msg))
            pss_sig = sig.read_bytes()
            if len(pss_sig) != bits // 8:
                sys.exit(f"signature length wrong at {name}")
            pss_out.append(c_array(
                f"{name}_pss_sig", pss_sig,
                f"openssl dgst -sha256 -sign key{bits}.pem -sigopt rsa_padding_mode:pss\n"
                f"  -sigopt rsa_pss_saltlen:32 -sigopt rsa_mgf1_md:sha256 over\n"
                f"{name}_message: RSASSA-PSS under n{bits}."))

            digest384 = sh(ossl, "dgst", "-sha384", "-binary", str(msg))
            pkcs1_out.append(c_array(f"{name}_sha384_digest", digest384,
                                     f"openssl dgst -sha384 -binary over {name}_message."))
            for digest_name, digest in (("sha256", digest256), ("sha384", digest384)):
                sig = t / f"{name}.{digest_name}.sig"
                sig_bytes = pkcs1_sign(ossl, key, pub, digest_name, msg, sig, digest)
                if len(sig_bytes) != bits // 8:
                    sys.exit(f"signature length wrong at {name} {digest_name}")
                pkcs1_out.append(c_array(
                    f"{name}_{digest_name}_sig", sig_bytes,
                    f"openssl dgst -{digest_name} -sign key{bits}.pem over {name}_message:\n"
                    f"RSASSA-PKCS1-v1_5 under n{bits}."))
    pss_out.append("#endif")
    pkcs1_out.append("#endif")
    OUT_PSS.write_text("\n".join(pss_out) + "\n")
    OUT_PKCS1.write_text("\n".join(pkcs1_out) + "\n")
    print(f"wrote {OUT_PSS} and {OUT_PKCS1}")


if __name__ == "__main__":
    main()
