"""C header text for gen_webpki_corpus.py.

Pool deduplicates byte arrays by content, so a Name two anchors share,
or a Certificate message six chains share, is one symbol the table
rows point at. The header carries a clang-format off marker after its
typedefs, as test/x509_vectors.h does, so regeneration is byte-identical
under any clang-format version, or none.
"""

HEADER = """\
// Web PKI chain fixtures for the TRUST=webpki verifier. Generated by
// test/gen_webpki_corpus.py from the fixed keys under test/webpki_corpus/keys/
// and the captures under test/webpki_captures/; regenerate, never edit.
// Produced with {version}.
//
// Two tables, doing different jobs (docs/webpki.md, "Verification"):
// webpki_corpus_chains holds the minted chains that test the logic, one
// rule per negative row; webpki_capture_chains holds the four public
// chains that test the bounds, one of them at two values of now_seconds.
// Every row is one call's inputs and the verdict it must reach: the exact
// RFC 9846 section 4.4.2 Certificate message bytes, the anchors, the
// hostname and now_seconds.
#ifndef CH_TEST_WEBPKI_CORPUS_H
#define CH_TEST_WEBPKI_CORPUS_H

#include <stddef.h>
#include <stdint.h>

// One trust anchor, as docs/webpki.md's "Trust anchors" defines it: the
// subject Name as its DER Name TLV and the public key as its DER
// SubjectPublicKeyInfo TLV.
typedef struct {{
    const uint8_t *name;
    size_t name_len;
    const uint8_t *spki;
    size_t spki_len;
}} webpki_corpus_anchor;

// One chain. expected is "ok", or the name of the one rule the chain
// breaks, as gen_webpki_corpus.py spells it. openssl_accepts is the
// verdict of `openssl verify -purpose sslserver -verify_hostname
// hostname -attime now_seconds` with the anchors as -CAfile, recorded so
// the rows where this mode is stricter than openssl are visible here.
typedef struct {{
    const char *name;
    const uint8_t *message;
    size_t message_len;
    const webpki_corpus_anchor *anchors;
    size_t anchor_count;
    const char *hostname;
    uint64_t now_seconds;
    const char *expected;
    int openssl_accepts;
}} webpki_corpus_chain;

// clang-format off
"""

FOOTER = """\
// clang-format on

#endif
"""


def c_array(name, data):
    lines = [f"static const uint8_t {name}[{len(data)}] = {{"]
    for off in range(0, len(data), 16):
        row = ", ".join(f"0x{b:02x}" for b in data[off : off + 16])
        comma = "," if off + 16 < len(data) else ""
        lines.append(f"    {row}{comma}")
    lines.append("};")
    return "\n".join(lines) + "\n"


class Pool:
    """Content-addressed byte arrays under one symbol prefix. The first
    label to add a content names its symbol; a later identical content
    reuses it."""

    def __init__(self, prefix):
        self.prefix = prefix
        self.symbols = {}  # bytes -> symbol
        self.order = []  # (symbol, bytes, comment)

    def add(self, label, data, comment):
        if data in self.symbols:
            return self.symbols[data]
        symbol = f"{self.prefix}_{label}"
        self.symbols[data] = symbol
        self.order.append((symbol, data, comment))
        return symbol

    def render(self):
        out = []
        for symbol, data, comment in self.order:
            out.append(f"// {comment}")
            out.append(c_array(symbol, data))
        return "\n".join(out)


def anchor_set(symbol, anchors):
    """anchors is a list of (name_symbol, spki_symbol, comment)."""
    lines = [f"static const webpki_corpus_anchor {symbol}[{len(anchors)}] = {{"]
    for name, spki, comment in anchors:
        lines.append(f"    // {comment}")
        lines.append(f"    {{{name}, sizeof {name}, {spki}, sizeof {spki}}},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def chain_table(symbol, rows):
    """rows is a list of dicts with the row's fields and a note."""
    lines = [f"static const webpki_corpus_chain {symbol}[{len(rows)}] = {{"]
    for row in rows:
        for line in row["note"].splitlines():
            lines.append(f"    // {line}")
        lines.append("    {")
        lines.append(f'        "{row["name"]}",')
        lines.append(f'        {row["message"]}, sizeof {row["message"]},')
        lines.append(f'        {row["anchors"]}, {row["anchor_count"]},')
        lines.append(f'        "{row["hostname"]}", {row["now_seconds"]}ULL,')
        lines.append(f'        "{row["expected"]}", {int(row["openssl_accepts"])},')
        lines.append("    },")
    lines.append("};")
    return "\n".join(lines) + "\n"
