// The provisioning walk. Contract in x509_ca.h.
//
// This reads the certificate's SubjectPublicKeyInfo and its
// basicConstraints, and nothing else. It decides no trust: it returns
// bytes, never a verdict, and it is unreachable from any path that
// peer input takes. x509.c's parse_tbs is not reusable here for two
// reasons -- it demands the build's own signature algorithm, which a
// trust anchor need not use, and its basicConstraints compare admits
// only pathLen 0, which a root generated by docs/ca.md's own recipe
// does not carry.
#include "x509_ca.h"

#include <string.h>

#include "buf.h"
#include "cfg.h"
#include "ch_assert.h"
#include "ct.h"
#include "pem.h"
#include "x509.h"

// [0] EXPLICIT version, v3. Same encoding x509.c pins.
static const uint8_t version_v3[] = {0xa0, 0x03, 0x02, 0x01, 0x02};
// id-ce-basicConstraints and id-ce-keyUsage (RFC 5280 sections
// 4.2.1.9 and 4.2.1.3), OID bodies only.
static const uint8_t oid_basic_constraints[] = {0x55, 0x1d, 0x13};
static const uint8_t oid_key_usage[] = {0x55, 0x1d, 0x0f};
// keyCertSign, the bit that says this key signs certificates.
#define KEY_CERT_SIGN 0x04
// BOOLEAN TRUE, the cA field. DER admits one encoding of true.
static const uint8_t ca_true[] = {0x01, 0x01, 0xff};

static int oid_is(const x509_extension *ext, const uint8_t *want, size_t n) {
    return ext->oid_len == n && ct_memeq(ext->oid, want, n) != 0;
}

// basicConstraints on a trust anchor: cA TRUE, with pathLenConstraint
// absent (a self-signed root emits 30 03 01 01 ff) or present (an
// intermediate emits 30 06 01 01 ff 02 01 00). Both are accepted --
// an operator may pin either, and the device cannot tell them apart
// by anything it reads.
static int is_ca_true(const x509_extension *ext) {
    rbuf v;
    rb_init(&v, ext->value, ext->value_len);
    size_t len = 0;
    if (!x509_read_header(&v, 0x30, &len) || len != rb_left(&v)) {
        return 0;
    }
    if (!x509_read_exact(&v, ca_true, sizeof ca_true)) {
        return 0; // cA absent or FALSE: a leaf, not an anchor
    }
    if (rb_left(&v) != 0 && !x509_skip(&v, 0x02)) {
        return 0; // anything but a pathLenConstraint INTEGER
    }
    return !v.err && rb_left(&v) == 0;
}

// One extension. Returns 1 to accept it, 0 to reject the certificate.
// Sets *is_ca when this is the basicConstraints that says CA.
static int check_extension(const x509_extension *ext, int *is_ca) {
    if (oid_is(ext, oid_basic_constraints, sizeof oid_basic_constraints)) {
        if (*is_ca != 0 || !is_ca_true(ext)) {
            return 0; // a duplicate extnID, or not a CA
        }
        *is_ca = 1;
        return 1;
    }
    if (oid_is(ext, oid_key_usage, sizeof oid_key_usage)) {
        // Same rule x509.c applies to a chain intermediate (its
        // check_extension_value passes 0x04 for is_ca), and the same
        // reason: an anchor whose own keyUsage forbids signing
        // certificates cannot anchor a chain. This catches operator
        // error, not an attacker -- whoever can substitute the blob
        // can set the bit.
        //
        // Unlike x509.c the extension may be absent, because a
        // self-signed root commonly omits it. RFC 5280 section 4.2.1.3
        // makes it optional and says conforming CAs SHOULD mark it
        // critical, which is why it needs a case here at all: without
        // one it would fail the unknown-critical rule below and reject
        // every real intermediate.
        return x509_read_keyusage(ext->value, ext->value_len, KEY_CERT_SIGN) != 0;
    }
    // RFC 5280 section 4.2: an unrecognized critical extension MUST be
    // rejected. Unknown non-critical ones go unread, which is how the
    // subject and authority key identifiers pass.
    return !ext->critical;
}

// The extension list. Returns 1 only when basicConstraints said CA.
static int walk_extensions(rbuf *t) {
    size_t wrap_len = 0;
    if (!x509_read_header(t, 0xa3, &wrap_len)) {
        return 0;
    }
    const uint8_t *wrap = rb_bytes(t, wrap_len);
    if (wrap == NULL) {
        return 0;
    }
    rbuf w;
    rb_init(&w, wrap, wrap_len);
    size_t list_len = 0;
    if (!x509_read_header(&w, 0x30, &list_len) || list_len == 0 || list_len != rb_left(&w)) {
        return 0; // Extensions is SIZE (1..MAX) and fills its wrapper
    }
    int is_ca = 0;
    int count = 0;
    while (rb_left(&w) > 0) {
        x509_extension ext;
        if (++count > CH_X509_EXT_COUNT_MAX ||
            !x509_read_extension(&w, CH_X509_EXT_TLV_MAX, &ext) || !check_extension(&ext, &is_ca)) {
            return 0;
        }
    }
    return is_ca;
}

// The TBSCertificate fields, in DER order. Four are skipped whole:
// signatureAlgorithm is the anchor's own, which this never checks;
// issuer and subject are names, which this profile does not read; and
// validity needs a clock the device does not have.
static int walk_tbs(const uint8_t *tbs, size_t tbs_len, const uint8_t **key, size_t *key_len) {
    rbuf t;
    rb_init(&t, tbs, tbs_len);
    if (!x509_read_exact(&t, version_v3, sizeof version_v3) || !x509_read_serial(&t)) {
        return 0;
    }
    for (int i = 0; i < 4; i++) {
        if (!x509_skip(&t, 0x30)) {
            return 0;
        }
    }
    if (!x509_read_spki(&t, key, key_len)) {
        return 0;
    }
    if (!walk_extensions(&t)) {
        return 0;
    }
    return !t.err && rb_left(&t) == 0;
}

static int walk_certificate(const uint8_t *der, size_t der_len, const uint8_t **key,
                            size_t *key_len) {
    rbuf r;
    rb_init(&r, der, der_len);
    size_t body_len = 0;
    if (!x509_read_header(&r, 0x30, &body_len) || body_len != rb_left(&r)) {
        return 0;
    }
    size_t tbs_len = 0;
    if (!x509_read_header(&r, 0x30, &tbs_len)) {
        return 0;
    }
    const uint8_t *tbs = rb_bytes(&r, tbs_len);
    if (tbs == NULL || !walk_tbs(tbs, tbs_len, key, key_len)) {
        return 0;
    }
    // The signature's framing is checked and its bytes are not. A
    // self-signature proves nothing, so verifying it would only tell
    // an integrator a check happened. Reading the framing costs two
    // calls and rejects a certificate truncated after the TBS.
    const uint8_t *sig = NULL;
    size_t sig_len = 0;
    if (!x509_skip(&r, 0x30) || !x509_read_bitstring(&r, &sig, &sig_len) || sig_len == 0) {
        return 0;
    }
    return !r.err && rb_left(&r) == 0;
}

int ch_pubkey_from_pem(const uint8_t *pem, size_t pem_len, uint8_t der[CH_X509_MAX],
                       uint8_t key[CH_X509_KEY_MAX], size_t *key_len) {
    CH_ASSERT(der != NULL && key != NULL && key_len != NULL);
    CH_ASSERT(pem != NULL || pem_len == 0);
    // Cleared first, and again on every failure below, because
    // x509_read_spki leaves its outputs set on some rejecting paths:
    // the RSA arm fills them before the exponent compare can fail.
    *key_len = 0;
    ct_wipe(key, CH_X509_KEY_MAX);

    size_t der_len = 0;
    if (pem_decode_certificate(pem, pem_len, der, &der_len) != CH_OK) {
        return CH_EINVAL;
    }
    const uint8_t *spki = NULL;
    size_t spki_len = 0;
    if (!walk_certificate(der, der_len, &spki, &spki_len)) {
        return CH_EINVAL;
    }
    if (spki_len == 0 || spki_len > CH_X509_KEY_MAX) {
        return CH_EINVAL; // x509_read_spki's own range, restated at the boundary
    }
    memcpy(key, spki, spki_len);
    *key_len = spki_len;
    return CH_OK;
}
